#!/usr/bin/perl
use strict;
#
# A simple Perl script to read in a CSV file and dump out appropriate
# information so that a student's GPA may be produced by another program.
#
# Arguments are name of input file. name of output file, and Faculty
# of interest.

# The first four characters of the title of the input file should be the year.
#
# Headers in CSV file are:
# Owning School Clevel, Paper Occurrence, Credits, Name, Student ID,
# School of Study Clevel, Date of Birth, Result Status, Blank column.
#
# Then there are # 11 columns of passing grades (but just 10 columns prior
# to 2016), # 7 columns of failing grades including # ... and NC (but
# just 6 columns prior to 2014). Script will exit if year is before 2014.
# 
# Output is in the form of a CSV file.
#
open(GRADEDATA,$ARGV[0]);
open(OUTPUT,">>$ARGV[1]");

my $year = substr($ARGV[0], 0, 4);
my $cols;
my @allgrades;
my @gpanum;
my $gpaval;

if ($year < 2016) {
   $cols = 27;
   @allgrades = qw(A+ A A- B+ B B- C+ C P RP IC ... D E F NC WD);
# In GPA calculation, we ignore P, ..., F and NC.
   @gpanum = qw(9 8 7 6 5 4 3 2 -1 1 0 -1 0 0 -1 -1 0);
} else {
   $cols = 28;
   @allgrades = qw(A+ A A- B+ B B- C+ C C- P RP IC ... D E F NC WD);
   @gpanum = qw(9 8 7 6 5 4 3 2 1 -1 0 0 -1 0 0 -1 -1 0);
}
if ($year < 2014) {
   printf "Warning: The year is prior to 2014 so this script will exit.\n";
   exit;
}

my $start = 0;

while (<GRADEDATA>) {
   $start += 1;
#  Ignore first five header lines.
   if ($start > 5) {
      my @grade = split(/,/,$_);
      my $faculty = $grade[0];
      my $papercode = $grade[1];
      my $credits = $grade[2];
      my $name1 = $grade[3];
      $name1 =~ s/^"//;
      my $name2 = $grade[4];
      $name2 =~ s/"$//;
      my $id = $grade[5];
      my $stufaculty = $grade[6];
      my $birth = $grade[7];
      

      if (index($grade[8],"Total") > -1 and index($stufaculty,$ARGV[2]) > -1) {

         my $finalgrade = "MISSING";
         for (my $i = 10; $i < $cols; $i++) {
             if ($grade[$i] eq "1") {
                $finalgrade = $allgrades[$i-10];
                $gpaval = $gpanum[$i-10];
             }
         }
         if ($finalgrade ne "MISSING") {
            printf OUTPUT "%s; %s, %s, %s, %s, %d, %s, %d\n", $name1, $name2,  $id, $birth, $papercode, $credits, $finalgrade, $gpaval;
        }
      }
   }
}
